site_name: checkatlas
theme: readthedocs
repo_url: https://github.com/becavin-lab/checkatlas
site_url: https://checkatlas.readthedocs.io/

nav:
  - Overview:
    - Summary: "index.md"
    - Installation: "installation.md"
    - Usage: "usage.md"
    - Examples: "examples/examples.md"
    - Contributing: "contributing.md"
  - Metrics:
    - Summary: "metrics/metrics.md"
    - Clustering: "metrics/clustering.md"
    - Classification: "metrics/cell_annotation.md"
    - Dimensionality reduction: "metrics/dim_red.md"
    - Luca: "metrics/luca/all_metrics.md"
    - Add your own: "metrics/add_own.md"
  - API:
    - API: "API.md"


plugins:
  - search
  - mkdocstrings:
      enabled: !ENV [ ENABLE_MKDOCSTRINGS, true ]
      default_handler: python
      handlers:
        python:
          import:
            - https://docs.python-requests.org/en/master/objects.inv
          options:
            show_source: true
            heading_level: 4

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML
markdown_extensions:
  - mdx_math